### ISSUE TITLE
Incompatible with Terraformers mods

### ISSUE THREAD

**Issue by Valokki** [DavidGmc18/Nature_Arise_PUBLIC#5] opened 2023-12-11 21:48 UTC
When using [Terrestria](https://modrinth.com/mod/terrestria) or/and [Traverse](https://www.modrinth.com/mod/traverse) with Nature Arise there is massive amount of "terrablender:deferred_placeholder" biomes in world.

What you need to reproduce
- Minecraft 1.20.1 - 1.20.4
- Fabric API
- Nature Arise
- TerraBlender
- Traverse
- Terrestria

There is no issues if either Nature Arise or Terraformers mods are disabled.

Traverse and Terrestria doesn't seem to cause issues with other mods that use TerraBlender.

**Comment by DavidGmc18** [comment] 2023-12-14 18:19
I am working on fixing this issue. It may take longer to fix, beacuse this may be something wrong in Terrablender or Terraformers mods. I am still investigating why this happens.

**Comment by DavidGmc18** [comment] 2023-12-15 17:29
I discussed this issue with the Terrablender developer, and he believes the problem is on the TerraformersMC side. I will keep you posted on updates.

**Comment by DavidGmc18** [comment] 2023-12-15 19:52
Biolith (mod that caused this issue) is going to be fixed soon for 1.20+
I am closing this since there is nothing to be fixed on NA side.

**Closed as completed by DavidGmc18** 2023-12-15 19:52 UTC
Labels: not NA issue
